
version: '3'

services:
  db:
    container_name: demo
    image: postgres:12
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
    - /var/lib/postgresql